#!/bin/bash
#
# 8-10-2012 bart.verheyde@ugent.be
# 6-1-2013 bart.verheyde@ugent.be V 1.0
# 21-8-2013 bart.verheyde@ugent.be V 1.1
# geeft lijst met van genomes met hun directory en label code
# "bacterie directorie naam"	"pad tot bacterie directorie" "label code"
# Zymomonas_mobilis_NCIMB_11163_uid41019 ../../genomes/bacteria/complete/Zymomonas_mobilis_NCIMB_11163_uid41019 ba1
#result is saved in same directory as source file

# create_label_list <sequence list file> 

#opent bestand en leest het lijn voor lijn
#per lijn word er een bacterie code aan toegevoegde

awk '
BEGIN {
}
{
#labelcode eerste 3 letters van bacterie naam+lijnr
label_code= substr ($1, 0, 4) NR

	lijn=sprintf ("%s\t%s",$0,label_code)
	print lijn
 } # Action for everyline in a file
END {}
' $1 \
> $1.input
#Resultaat word opgeslagen in bestandsnaam.input

#creatie van label list file horend bij input
#formaat: BU01	Burkholderia lata 383T
#
awk '
BEGIN { }
{

#labelcode eerste 3 letters van bacterie naam+lijnr
#use $NF for last colum
label_code= $NF
	
	bacterie=$1
	#String bacterie dir opkuisen naar gewenste output _ -> " "
	gsub("_", " ",bacterie)

        #lijn=sprintf ("%s\t%s\t%s",label_code,bacterie_dir,$1)
        lijn=sprintf ("%s\t%s",label_code,bacterie)
        print lijn


} # Action for everyline in a file
END {}
' $1.input \
> $1.label
#Resultaat word opgeslagen in bestandsnaam.label
#
#
